#!/usr/bin/env python3
"""
Helper script to create the .env file with your custom paths.
"""

import os
from pathlib import Path


def main():
    print("=" * 80)
    print("📝 Instagram Assistant Environment Configuration")
    print("=" * 80)
    print()

    env_file = Path(__file__).parent / ".env"

    if env_file.exists():
        response = input("⚠️  A .env file already exists. Do you want to recreate it? (y/N): ")
        if response.lower() != 'y':
            print("Cancelled.")
            return

    print("I will ask you a few questions to configure your paths.\n")

    # Base directory (auto-detect)
    base_dir = Path(__file__).parent
    print(f"✓ Base directory detected: {base_dir}\n")

    # Instagram export directory
    print("1️⃣  Path to your Instagram export")
    print("   (Folder containing conversations, e.g., .../messages/inbox)")
    instagram_export = input("   Path: ").strip()
    if not instagram_export:
        instagram_export = str(Path.home() / "Documents/your_instagram_activity/messages/inbox")
        print(f"   → Default: {instagram_export}")

    # Conversations directory
    print("\n2️⃣  Directory to store converted conversations (relative to project)")
    conversations_dir = input("   Name (default: instagram_conversations): ").strip()
    if not conversations_dir:
        conversations_dir = "instagram_conversations"

    # Index directory
    print("\n3️⃣  Directory to store RAG indexes (relative to project)")
    index_dir = input("   Name (default: rag_data): ").strip()
    if not index_dir:
        index_dir = "rag_data"

    # User name
    print("\n4️⃣  Your first name (used in the interface)")
    user_name = input("   Name: ").strip()
    if not user_name:
        user_name = "Ismaël"

    # LLM Model
    print("\n5️⃣  Ollama model to use")
    llm_model = input("   Model (default: qwen3:latest): ").strip()
    if not llm_model:
        llm_model = "qwen3:latest"

    # Create .env file
    env_content = f"""# Instagram Assistant Configuration
# Automatically generated by scripts/setup/setup_env.py

# === Instagram Paths ===
INSTAGRAM_EXPORT_DIR={instagram_export}

# === Project Paths ===
BASE_DIR={base_dir}
CONVERSATIONS_DIR={conversations_dir}
INDEX_DIR={index_dir}

# === User Configuration ===
USER_NAME={user_name}

# === LLM Configuration ===
LLM_MODEL={llm_model}
OLLAMA_URL=http://localhost:11434
LLM_NUM_CTX=8192

# === Embeddings Configuration ===
EMBEDDING_MODEL=BAAI/bge-m3
USE_GPU=true

# === RAG Configuration ===
TOP_K=5
MIN_SIMILARITY=0.3
USE_RERANKING=true
USE_HYBRID=true

# === Chunking Configuration ===
CHUNK_MAX_MESSAGES=50
CHUNK_MAX_DAYS=3
CHUNK_OVERLAP=5
"""

    with open(env_file, 'w', encoding='utf-8') as f:
        f.write(env_content)

    print("\n" + "=" * 80)
    print("✅ .env file created successfully!")
    print("=" * 80)
    print(f"\n📁 File: {env_file}")
    print("\nYou can modify this file manually if needed.")
    print("\n🚀 Next steps:")
    print("   1. Install dependencies: pip install -r requirements.txt")
    print("   2. Convert your conversations: python3 scripts/ingestion/instagram_to_text.py")
    print("   3. Create the index: python3 setup_rag_batch.py")
    print("   4. Launch the application: python3 app.py")


if __name__ == "__main__":
    main()